# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/pierr/Desktop/MinesParisTech/UE-12/Meuhjon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/pierr/Desktop/MinesParisTech/UE-12/Meuhjon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /mnt/c/Users/pierr/Desktop/MinesParisTech/UE-12/Meuhjon/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/pierr/Desktop/MinesParisTech/UE-12/Meuhjon/CMakeFiles /mnt/c/Users/pierr/Desktop/MinesParisTech/UE-12/Meuhjon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/pierr/Desktop/MinesParisTech/UE-12/Meuhjon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named meuhjon

# Build rule for target.
meuhjon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 meuhjon
.PHONY : meuhjon

# fast build rule for target.
meuhjon/fast:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/build
.PHONY : meuhjon/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/main.cpp.s
.PHONY : main.cpp.s

src/dialogue.o: src/dialogue.cpp.o

.PHONY : src/dialogue.o

# target to build an object file
src/dialogue.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/dialogue.cpp.o
.PHONY : src/dialogue.cpp.o

src/dialogue.i: src/dialogue.cpp.i

.PHONY : src/dialogue.i

# target to preprocess a source file
src/dialogue.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/dialogue.cpp.i
.PHONY : src/dialogue.cpp.i

src/dialogue.s: src/dialogue.cpp.s

.PHONY : src/dialogue.s

# target to generate assembly for a file
src/dialogue.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/dialogue.cpp.s
.PHONY : src/dialogue.cpp.s

src/display.o: src/display.cpp.o

.PHONY : src/display.o

# target to build an object file
src/display.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/display.cpp.o
.PHONY : src/display.cpp.o

src/display.i: src/display.cpp.i

.PHONY : src/display.i

# target to preprocess a source file
src/display.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/display.cpp.i
.PHONY : src/display.cpp.i

src/display.s: src/display.cpp.s

.PHONY : src/display.s

# target to generate assembly for a file
src/display.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/display.cpp.s
.PHONY : src/display.cpp.s

src/ennemi.o: src/ennemi.cpp.o

.PHONY : src/ennemi.o

# target to build an object file
src/ennemi.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/ennemi.cpp.o
.PHONY : src/ennemi.cpp.o

src/ennemi.i: src/ennemi.cpp.i

.PHONY : src/ennemi.i

# target to preprocess a source file
src/ennemi.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/ennemi.cpp.i
.PHONY : src/ennemi.cpp.i

src/ennemi.s: src/ennemi.cpp.s

.PHONY : src/ennemi.s

# target to generate assembly for a file
src/ennemi.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/ennemi.cpp.s
.PHONY : src/ennemi.cpp.s

src/hero.o: src/hero.cpp.o

.PHONY : src/hero.o

# target to build an object file
src/hero.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/hero.cpp.o
.PHONY : src/hero.cpp.o

src/hero.i: src/hero.cpp.i

.PHONY : src/hero.i

# target to preprocess a source file
src/hero.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/hero.cpp.i
.PHONY : src/hero.cpp.i

src/hero.s: src/hero.cpp.s

.PHONY : src/hero.s

# target to generate assembly for a file
src/hero.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/hero.cpp.s
.PHONY : src/hero.cpp.s

src/personnage.o: src/personnage.cpp.o

.PHONY : src/personnage.o

# target to build an object file
src/personnage.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/personnage.cpp.o
.PHONY : src/personnage.cpp.o

src/personnage.i: src/personnage.cpp.i

.PHONY : src/personnage.i

# target to preprocess a source file
src/personnage.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/personnage.cpp.i
.PHONY : src/personnage.cpp.i

src/personnage.s: src/personnage.cpp.s

.PHONY : src/personnage.s

# target to generate assembly for a file
src/personnage.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/personnage.cpp.s
.PHONY : src/personnage.cpp.s

src/plateau.o: src/plateau.cpp.o

.PHONY : src/plateau.o

# target to build an object file
src/plateau.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/plateau.cpp.o
.PHONY : src/plateau.cpp.o

src/plateau.i: src/plateau.cpp.i

.PHONY : src/plateau.i

# target to preprocess a source file
src/plateau.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/plateau.cpp.i
.PHONY : src/plateau.cpp.i

src/plateau.s: src/plateau.cpp.s

.PHONY : src/plateau.s

# target to generate assembly for a file
src/plateau.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/plateau.cpp.s
.PHONY : src/plateau.cpp.s

src/potion.o: src/potion.cpp.o

.PHONY : src/potion.o

# target to build an object file
src/potion.cpp.o:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/potion.cpp.o
.PHONY : src/potion.cpp.o

src/potion.i: src/potion.cpp.i

.PHONY : src/potion.i

# target to preprocess a source file
src/potion.cpp.i:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/potion.cpp.i
.PHONY : src/potion.cpp.i

src/potion.s: src/potion.cpp.s

.PHONY : src/potion.s

# target to generate assembly for a file
src/potion.cpp.s:
	$(MAKE) -f CMakeFiles/meuhjon.dir/build.make CMakeFiles/meuhjon.dir/src/potion.cpp.s
.PHONY : src/potion.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... meuhjon"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/dialogue.o"
	@echo "... src/dialogue.i"
	@echo "... src/dialogue.s"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/ennemi.o"
	@echo "... src/ennemi.i"
	@echo "... src/ennemi.s"
	@echo "... src/hero.o"
	@echo "... src/hero.i"
	@echo "... src/hero.s"
	@echo "... src/personnage.o"
	@echo "... src/personnage.i"
	@echo "... src/personnage.s"
	@echo "... src/plateau.o"
	@echo "... src/plateau.i"
	@echo "... src/plateau.s"
	@echo "... src/potion.o"
	@echo "... src/potion.i"
	@echo "... src/potion.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

